umd_schoolwide_header:
  embed: '<script src="https://umd-header.umd.edu/build/bundle.js?search=1&search_domain=&events=0&news=0&schools=0&admissions=0&support=1&support_url=&wrapper=1100&sticky=0"></script>'
